In [4]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import re

In [44]:
t_eu = pd.read_csv('exoplanet.eu_catalog.csv')
# t_eu.set_index('# name', inplace=True)
# print(t_eu)
t_eu

,# name,planet_status,mass,mass_error_min,mass_error_max,mass_sini,mass_sini_error_min,mass_sini_error_max,radius,radius_error_min,...,star_sp_type,star_age,star_age_error_min,star_age_error_max,star_teff,star_teff_error_min,star_teff_error_max,star_detected_disc,star_magnetic_field,star_alternate_names
0,11 Com b,Confirmed,NaN,NaN,NaN,16.1284,1.500,1.500,NaN,NaN,...,G8 III,NaN,NaN,NaN,4742.0,100.0,100.0,NaN,NaN,NaN
1,11 Oph b,Confirmed,21.00,3.00,3.00,NaN,NaN,NaN,NaN,NaN,...,M9,0.011,0.002,0.002,2375.0,175.0,175.0,NaN,NaN,"Oph 1622-2405, Oph 11A"
2,11 UMi b,Confirmed,NaN,NaN,NaN,11.0873,1.100,1.100,NaN,NaN,...,K4III,1.560,0.540,0.540,4340.0,70.0,70.0,NaN,NaN,NaN
3,14 And b,Confirmed,NaN,NaN,NaN,4.6840,0.230,0.230,NaN,NaN,...,K0III,NaN,NaN,NaN,4813.0,20.0,20.0,NaN,NaN,NaN
4,14 Her b,Confirmed,9.10,NaN,NaN,5.2150,NaN,NaN,NaN,NaN,...,K0 V,5.100,NaN,NaN,5311.0,87.0,87.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5220,ups And c,Confirmed,9.10,2.93,5.04,1.8000,0.260,0.260,NaN,NaN,...,F8 V,3.800,1.000,1.000,6212.0,80.0,80.0,NaN,NaN,NaN
5221,ups And d,Confirmed,23.58,2.29,2.93,10.1900,NaN,NaN,NaN,NaN,...,F8 V,3.800,1.000,1.000,6212.0,80.0,80.0,NaN,NaN,NaN
5222,ups And e,Confirmed,NaN,NaN,NaN,1.0590,0.028,0.028,NaN,NaN,...,F8 V,3.800,1.000,1.000,6212.0,80.0,80.0,NaN,NaN,NaN
5223,ups Leo b,Confirmed,NaN,NaN,NaN,0.5100,0.260,0.080,NaN,NaN,...,G9 III,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5224,zet Del B,Confirmed,40.00,5.00,15.00,NaN,NaN,NaN,NaN,NaN,...,A3V,0.525,0.125,0.125,8336.0,NaN,NaN,NaN,NaN,"HD 196180, HIP 101589, 2MASS J20351852+1440272"

In [61]:
re_2mass = re.compile(r"^\s*(2MASS(\s|-)((J|H|K)?\d+(\+|-)\d+))")
re_bd = re.compile(r"^\s*(BD(\s|\+|-)(\d+\s\d+))")
re_hd = re.compile(r"^\s*(HD\s(\d+))")
re_hip = re.compile(r"^\s*(HIP\s(\d+))")
re_gj = re.compile(r"^\s*(GJ\s(\d+))")
re_tic = re.compile(r"^\s*(TIC\s(\d+))")
re_toi = re.compile(r"^\s*(TOI-(\d+))")
re_tyc = re.compile(r"^\s*(TYC\s(\d+(-\d+)*))")
def alt_name_cols(row):
    
    new_row = row.copy(deep=False)
    
    s_alt_names_str = str(row['star_alternate_names'])
    new_row['SNAME_2MASS'] = ""
    new_row['SNAME_BD'] = ""
    new_row['SNAME_HD'] = ""
    new_row['SNAME_HIP'] = ""
    new_row['SNAME_GJ'] = ""
    new_row['SNAME_TIC'] = ""
    new_row['SNAME_TOI'] = ""
    new_row['SNAME_TYC'] = ""
    
    s_name_list = s_alt_names_str.split(",")
    
    for s_name in s_name_list:
        m_2mass = re.search(re_2mass, s_name)
        if m_2mass is not None:
            new_row['SNAME_2MASS'] = m_2mass.group(3)
            continue
        
        m_bd = re.search(re_bd, s_name)
        if m_bd is not None:
            new_row['SNAME_BD'] = m_bd.group(3)
            continue
        
        m_hd = re.search(re_hd, s_name)
        if m_hd is not None:
            new_row['SNAME_HD'] = m_hd.group(2)
            continue
        
        m_hip = re.search(re_hip, s_name)
        if m_hip is not None:
            new_row['SNAME_HIP'] = m_hip.group(2)
            continue
                
        m_gj = re.search(re_gj, s_name)
        if m_gj is not None:
            new_row['SNAME_GJ'] = m_gj.group(2)
            continue
        
        m_tic = re.search(re_tic, s_name)
        if m_tic is not None:
            new_row['SNAME_TIC'] = m_tic.group(2)
            continue
        
        m_toi = re.search(re_toi, s_name)
        if m_toi is not None:
            new_row['SNAME_TOI'] = m_toi.group(2)
            continue
        
        m_tyc = re.search(re_tyc, s_name)
        if m_tyc is not None:
            new_row['SNAME_TYC'] = m_tyc.group(2)
            continue
            
    return new_row

In [52]:
newnames = t_eu.apply(alt_name_cols, axis=1)